In [1]:
import pandas as pd

In [2]:
#Импортируем все таблицы
sber = pd.read_csv('data/Прошлые данные - SBER.csv', sep=',')
gazp = pd.read_csv('data/Прошлые данные - GAZP.csv', sep=',')
abrd = pd.read_csv('data/Прошлые данные - ABRD.csv', sep=',')
afks = pd.read_csv('data/Прошлые данные - AFKS.csv', sep=',')
aflt = pd.read_csv('data/Прошлые данные - AFLT.csv', sep=',')
alrs = pd.read_csv('data/Прошлые данные - ALRS.csv', sep=',')
aqua = pd.read_csv('data/Прошлые данные - AQUA.csv', sep=',')
belu = pd.read_csv('data/Прошлые данные - BELU.csv', sep=',')
bspb = pd.read_csv('data/Прошлые данные - BSPB.csv', sep=',')
gche = pd.read_csv('data/Прошлые данные - GCHE.csv', sep=',')
gema = pd.read_csv('data/Прошлые данные - GEMA.csv', sep=',')
irao = pd.read_csv('data/Прошлые данные - IRAO.csv', sep=',')
iskj = pd.read_csv('data/Прошлые данные - ISKJ.csv', sep=',')
kazt = pd.read_csv('data/Прошлые данные - KAZT.csv', sep=',')
kmaz = pd.read_csv('data/Прошлые данные - KMAZ.csv', sep=',')
krsb = pd.read_csv('data/Прошлые данные - KRSB.csv', sep=',')
kzos = pd.read_csv('data/Прошлые данные - KZOS.csv', sep=',')
magn = pd.read_csv('data/Прошлые данные - MAGN.csv', sep=',')
mgnt = pd.read_csv('data/Прошлые данные - MGNT.csv', sep=',')
moex = pd.read_csv('data/Прошлые данные - MOEX.csv', sep=',')
mrkp = pd.read_csv('data/Прошлые данные - MRKP.csv', sep=',')
mstt = pd.read_csv('data/Прошлые данные - MSTT.csv', sep=',')
mtss = pd.read_csv('data/Прошлые данные - MTSS.csv', sep=',')
nknc = pd.read_csv('data/Прошлые данные - NKNC.csv', sep=',')
nlmk = pd.read_csv('data/Прошлые данные - NLMK.csv', sep=',')
nmtp = pd.read_csv('data/Прошлые данные - NMTP.csv', sep=',')
nvtk = pd.read_csv('data/Прошлые данные - NVTK.csv', sep=',')
phor = pd.read_csv('data/Прошлые данные - PHOR.csv', sep=',')
pikk = pd.read_csv('data/Прошлые данные - PIKK.csv', sep=',')
pmsb = pd.read_csv('data/Прошлые данные - PMSB.csv', sep=',')
rosn = pd.read_csv('data/Прошлые данные - ROSN.csv', sep=',')
rtkm = pd.read_csv('data/Прошлые данные - RTKM.csv', sep=',')
rual = pd.read_csv('data/Прошлые данные - RUAL.csv', sep=',')
sgzh = pd.read_csv('data/Прошлые данные - SGZH.csv', sep=',')
vtbr = pd.read_csv('data/Прошлые данные - VTBR.csv', sep=',')

In [3]:
#Переобразовываем метод object в float столбец цена
def price(s):
    i = str(s).find(',')
    if(i>0):
        return s[:i] + '.' + s[i+1:]
    else :
        return s 
    
def tochka(s):
    i = str(s).find('.')
    if(i>0):
        return s[:i] + '' + s[i+1:]
    else :
        return s

In [4]:
belu['Цена'] = belu['Цена'].apply(tochka)
gche['Цена'] = gche['Цена'].apply(tochka)
mgnt['Цена'] = mgnt['Цена'].apply(tochka)
mtss['Цена'] = mtss['Цена'].apply(tochka)
nvtk['Цена'] = nvtk['Цена'].apply(tochka)
phor['Цена'] = phor['Цена'].apply(tochka)
pikk['Цена'] = pikk['Цена'].apply(tochka)

In [5]:
#Применяем функцию с ценой
sber['Цена'] = sber['Цена'].apply(price)
gazp['Цена'] = gazp['Цена'].apply(price)
abrd['Цена'] = abrd['Цена'].apply(price)
afks['Цена'] = afks['Цена'].apply(price)
aflt['Цена'] = aflt['Цена'].apply(price)
alrs['Цена'] = alrs['Цена'].apply(price)
aqua['Цена'] = aqua['Цена'].apply(price)
belu['Цена'] = belu['Цена'].apply(price)
bspb['Цена'] = bspb['Цена'].apply(price)
gche['Цена'] = gche['Цена'].apply(price)
gema['Цена'] = gema['Цена'].apply(price)
irao['Цена'] = irao['Цена'].apply(price)
iskj['Цена'] = iskj['Цена'].apply(price)
kazt['Цена'] = kazt['Цена'].apply(price)
kmaz['Цена'] = kmaz['Цена'].apply(price)
krsb['Цена'] = krsb['Цена'].apply(price)
kzos['Цена'] = kzos['Цена'].apply(price)
magn['Цена'] = magn['Цена'].apply(price)
mgnt['Цена'] = mgnt['Цена'].apply(price)
moex['Цена'] = moex['Цена'].apply(price)
mrkp['Цена'] = mrkp['Цена'].apply(price)
mstt['Цена'] = mstt['Цена'].apply(price)
mtss['Цена'] = mtss['Цена'].apply(price)
nknc['Цена'] = nknc['Цена'].apply(price)
nlmk['Цена'] = nlmk['Цена'].apply(price)
nmtp['Цена'] = nmtp['Цена'].apply(price)
nvtk['Цена'] = nvtk['Цена'].apply(price)
phor['Цена'] = phor['Цена'].apply(price)
pikk['Цена'] = pikk['Цена'].apply(price)
pmsb['Цена'] = pmsb['Цена'].apply(price)
rosn['Цена'] = rosn['Цена'].apply(price)
rtkm['Цена'] = rtkm['Цена'].apply(price)
rual['Цена'] = rual['Цена'].apply(price)
sgzh['Цена'] = sgzh['Цена'].apply(price)
vtbr['Цена'] = vtbr['Цена'].apply(price)

In [6]:
#Меняем тип данных на float, столбец с ценой
sber['Цена'] = pd.to_numeric(sber['Цена'], errors='coerce')
gazp['Цена'] = pd.to_numeric(gazp['Цена'], errors='coerce')
abrd['Цена'] = pd.to_numeric(abrd['Цена'], errors='coerce')
afks['Цена'] = pd.to_numeric(afks['Цена'], errors='coerce')
aflt['Цена'] = pd.to_numeric(aflt['Цена'], errors='coerce')
alrs['Цена'] = pd.to_numeric(alrs['Цена'], errors='coerce')
aqua['Цена'] = pd.to_numeric(aqua['Цена'], errors='coerce')
belu['Цена'] = pd.to_numeric(belu['Цена'], errors='coerce')
bspb['Цена'] = pd.to_numeric(bspb['Цена'], errors='coerce')
gche['Цена'] = pd.to_numeric(gche['Цена'], errors='coerce')
gema['Цена'] = pd.to_numeric(gema['Цена'], errors='coerce')
irao['Цена'] = pd.to_numeric(irao['Цена'], errors='coerce')
iskj['Цена'] = pd.to_numeric(iskj['Цена'], errors='coerce')
kazt['Цена'] = pd.to_numeric(kazt['Цена'], errors='coerce')
kmaz['Цена'] = pd.to_numeric(kmaz['Цена'], errors='coerce')
krsb['Цена'] = pd.to_numeric(krsb['Цена'], errors='coerce')
kzos['Цена'] = pd.to_numeric(kzos['Цена'], errors='coerce')
magn['Цена'] = pd.to_numeric(magn['Цена'], errors='coerce')
mgnt['Цена'] = pd.to_numeric(mgnt['Цена'], errors='coerce')
moex['Цена'] = pd.to_numeric(moex['Цена'], errors='coerce')
mrkp['Цена'] = pd.to_numeric(mrkp['Цена'], errors='coerce')
mstt['Цена'] = pd.to_numeric(mstt['Цена'], errors='coerce')
mtss['Цена'] = pd.to_numeric(mtss['Цена'], errors='coerce')
nknc['Цена'] = pd.to_numeric(nknc['Цена'], errors='coerce')
nlmk['Цена'] = pd.to_numeric(nlmk['Цена'], errors='coerce')
nmtp['Цена'] = pd.to_numeric(nmtp['Цена'], errors='coerce')
nvtk['Цена'] = pd.to_numeric(nvtk['Цена'], errors='coerce')
phor['Цена'] = pd.to_numeric(phor['Цена'], errors='coerce')
pikk['Цена'] = pd.to_numeric(pikk['Цена'], errors='coerce')
pmsb['Цена'] = pd.to_numeric(pmsb['Цена'], errors='coerce')
rosn['Цена'] = pd.to_numeric(rosn['Цена'], errors='coerce')
rtkm['Цена'] = pd.to_numeric(rtkm['Цена'], errors='coerce')
rual['Цена'] = pd.to_numeric(rual['Цена'], errors='coerce')
sgzh['Цена'] = pd.to_numeric(sgzh['Цена'], errors='coerce')
vtbr['Цена'] = pd.to_numeric(vtbr['Цена'], errors='coerce')

In [7]:
#Меняем тип данных на datetime, столбец дата
sber['Дата'] = pd.to_datetime(sber['Дата'], dayfirst=True)
gazp['Дата'] = pd.to_datetime(gazp['Дата'], dayfirst=True)
abrd['Дата'] = pd.to_datetime(abrd['Дата'], dayfirst=True)
afks['Дата'] = pd.to_datetime(afks['Дата'], dayfirst=True)
aflt['Дата'] = pd.to_datetime(aflt['Дата'], dayfirst=True)
alrs['Дата'] = pd.to_datetime(alrs['Дата'], dayfirst=True)
aqua['Дата'] = pd.to_datetime(aqua['Дата'], dayfirst=True)
belu['Дата'] = pd.to_datetime(belu['Дата'], dayfirst=True)
bspb['Дата'] = pd.to_datetime(bspb['Дата'], dayfirst=True)
gche['Дата'] = pd.to_datetime(gche['Дата'], dayfirst=True)
gema['Дата'] = pd.to_datetime(gema['Дата'], dayfirst=True)
irao['Дата'] = pd.to_datetime(irao['Дата'], dayfirst=True)
iskj['Дата'] = pd.to_datetime(iskj['Дата'], dayfirst=True)
kazt['Дата'] = pd.to_datetime(kazt['Дата'], dayfirst=True)
kmaz['Дата'] = pd.to_datetime(kmaz['Дата'], dayfirst=True)
krsb['Дата'] = pd.to_datetime(krsb['Дата'], dayfirst=True)
kzos['Дата'] = pd.to_datetime(kzos['Дата'], dayfirst=True)
magn['Дата'] = pd.to_datetime(magn['Дата'], dayfirst=True)
mgnt['Дата'] = pd.to_datetime(mgnt['Дата'], dayfirst=True)
moex['Дата'] = pd.to_datetime(moex['Дата'], dayfirst=True)
mrkp['Дата'] = pd.to_datetime(mrkp['Дата'], dayfirst=True)
mstt['Дата'] = pd.to_datetime(mstt['Дата'], dayfirst=True)
mtss['Дата'] = pd.to_datetime(mtss['Дата'], dayfirst=True)
nknc['Дата'] = pd.to_datetime(nknc['Дата'], dayfirst=True)
nlmk['Дата'] = pd.to_datetime(nlmk['Дата'], dayfirst=True)
nmtp['Дата'] = pd.to_datetime(nmtp['Дата'], dayfirst=True)
nvtk['Дата'] = pd.to_datetime(nvtk['Дата'], dayfirst=True)
phor['Дата'] = pd.to_datetime(phor['Дата'], dayfirst=True)
pikk['Дата'] = pd.to_datetime(pikk['Дата'], dayfirst=True)
pmsb['Дата'] = pd.to_datetime(pmsb['Дата'], dayfirst=True)
rosn['Дата'] = pd.to_datetime(rosn['Дата'], dayfirst=True)
rtkm['Дата'] = pd.to_datetime(rtkm['Дата'], dayfirst=True)
rual['Дата'] = pd.to_datetime(rual['Дата'], dayfirst=True)
sgzh['Дата'] = pd.to_datetime(sgzh['Дата'], dayfirst=True)
vtbr['Дата'] = pd.to_datetime(vtbr['Дата'], dayfirst=True)

In [8]:
# Переименовываем имена столбцов
sber.rename(columns={'Дата': 'date', 'Цена':'pr_sber'}, inplace=True)
abrd.rename(columns={'Дата': 'date', 'Цена':'pr_abrd'}, inplace=True)
afks.rename(columns={'Дата': 'date', 'Цена':'pr_afks'}, inplace=True)
aflt.rename(columns={'Дата': 'date', 'Цена':'pr_aflt'}, inplace=True)
alrs.rename(columns={'Дата': 'date', 'Цена':'pr_alrs'}, inplace=True)
aqua.rename(columns={'Дата': 'date', 'Цена':'pr_aqua'}, inplace=True)
belu.rename(columns={'Дата': 'date', 'Цена':'pr_belu'}, inplace=True)
bspb.rename(columns={'Дата': 'date', 'Цена':'pr_bspb'}, inplace=True)
gazp.rename(columns={'Дата': 'date', 'Цена':'pr_gazp'}, inplace=True)
gche.rename(columns={'Дата': 'date', 'Цена':'pr_gche'}, inplace=True)
gema.rename(columns={'Дата': 'date', 'Цена':'pr_gema'}, inplace=True)
irao.rename(columns={'Дата': 'date', 'Цена':'pr_irao'}, inplace=True)
iskj.rename(columns={'Дата': 'date', 'Цена':'pr_iskj'}, inplace=True)
kazt.rename(columns={'Дата': 'date', 'Цена':'pr_kazt'}, inplace=True)
kmaz.rename(columns={'Дата': 'date', 'Цена':'pr_kmaz'}, inplace=True)
krsb.rename(columns={'Дата': 'date', 'Цена':'pr_krsb'}, inplace=True)
kzos.rename(columns={'Дата': 'date', 'Цена':'pr_kzos'}, inplace=True)
magn.rename(columns={'Дата': 'date', 'Цена':'pr_magn'}, inplace=True)
mgnt.rename(columns={'Дата': 'date', 'Цена':'pr_mgnt'}, inplace=True)
moex.rename(columns={'Дата': 'date', 'Цена':'pr_moex'}, inplace=True)
mrkp.rename(columns={'Дата': 'date', 'Цена':'pr_mrkp'}, inplace=True)
mstt.rename(columns={'Дата': 'date', 'Цена':'pr_mstt'}, inplace=True)
mtss.rename(columns={'Дата': 'date', 'Цена':'pr_mtss'}, inplace=True)
nknc.rename(columns={'Дата': 'date', 'Цена':'pr_nknc'}, inplace=True)
nlmk.rename(columns={'Дата': 'date', 'Цена':'pr_nlmk'}, inplace=True)
nmtp.rename(columns={'Дата': 'date', 'Цена':'pr_nmtp'}, inplace=True)
nvtk.rename(columns={'Дата': 'date', 'Цена':'pr_nvtk'}, inplace=True)
phor.rename(columns={'Дата': 'date', 'Цена':'pr_phor'}, inplace=True)
pikk.rename(columns={'Дата': 'date', 'Цена':'pr_pikk'}, inplace=True)
pmsb.rename(columns={'Дата': 'date', 'Цена':'pr_pmsb'}, inplace=True)
rosn.rename(columns={'Дата': 'date', 'Цена':'pr_rosn'}, inplace=True)
rtkm.rename(columns={'Дата': 'date', 'Цена':'pr_rtkm'}, inplace=True)
rual.rename(columns={'Дата': 'date', 'Цена':'pr_rual'}, inplace=True)
sgzh.rename(columns={'Дата': 'date', 'Цена':'pr_sgzh'}, inplace=True)
vtbr.rename(columns={'Дата': 'date', 'Цена':'pr_vtbr'}, inplace=True)

In [9]:
# Удаляю не неужные столбцы
sber = sber.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
gazp = gazp.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
abrd = abrd.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
afks = afks.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
aflt = aflt.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
alrs = alrs.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
aqua = aqua.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
belu = belu.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
bspb = bspb.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
gche = gche.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
gema = gema.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
irao = irao.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
iskj = iskj.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
kazt = kazt.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
kmaz = kmaz.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
krsb = krsb.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
kzos = kzos.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
magn = magn.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
mgnt = mgnt.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
moex = moex.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
mrkp = mrkp.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
mstt = mstt.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
mtss = mtss.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
nknc = nknc.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
nlmk = nlmk.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
nmtp = nmtp.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
nvtk = nvtk.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
phor = phor.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
pikk = pikk.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
pmsb = pmsb.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
rosn = rosn.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
rtkm = rtkm.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
rual = rual.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
sgzh = sgzh.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)
vtbr = vtbr.drop(['Откр.', 'Макс.', 'Мин.', 'Объём','Изм. %'], axis=1)

In [10]:
# Объеденяю таблицы
ab_af = gema.merge(abrd, how='outer', on='date')
af_af = ab_af.merge(alrs, how='outer', on='date')
af_al = af_af.merge(afks, how='outer', on='date')
al_aq = af_al.merge(aflt, how='outer', on='date')
aq_be = al_aq.merge(bspb, how='outer', on='date')
be_bs = aq_be.merge(belu, how='outer', on='date')
bs_ga = be_bs.merge(vtbr, how='outer', on='date')
ga_gc = bs_ga.merge(gazp, how='outer', on='date')
gc_ge = ga_gc.merge(gche, how='outer', on='date')
ge_ir = gc_ge.merge(aqua, how='outer', on='date')
ir_is = ge_ir.merge(irao, how='outer', on='date')
is_ka = ir_is.merge(iskj, how='outer', on='date')
ka_km = is_ka.merge(kzos, how='outer', on='date')
km_kr = ka_km.merge(kmaz, how='outer', on='date')
kr_kz = km_kr.merge(krsb, how='outer', on='date')
kz_ma = kr_kz.merge(kazt, how='outer', on='date')
ma_mg = kz_ma.merge(mgnt, how='outer', on='date')
mg_mo = ma_mg.merge(magn, how='outer', on='date')
mo_mr = mg_mo.merge(moex, how='outer', on='date')
mr_ms = mo_mr.merge(mstt, how='outer', on='date')
ms_mt = mr_ms.merge(mtss, how='outer', on='date')
mt_nk = ms_mt.merge(nknc, how='outer', on='date')
nk_nl = mt_nk.merge(nlmk, how='outer', on='date')
nl_nm = nk_nl.merge(nmtp, how='outer', on='date')
nm_nv = nl_nm.merge(nvtk, how='outer', on='date')
nv_ph = nm_nv.merge(pmsb, how='outer', on='date')
ph_pi = nv_ph.merge(pikk, how='outer', on='date')
pi_pm = ph_pi.merge(rosn, how='outer', on='date')
pm_ro = pi_pm.merge(mrkp, how='outer', on='date')
ro_rt = pm_ro.merge(rtkm, how='outer', on='date')
rt_ru = ro_rt.merge(rual, how='outer', on='date')
ru_sb = rt_ru.merge(sber, how='outer', on='date')
sb_sg = ru_sb.merge(sgzh, how='outer', on='date')
stat = sb_sg.merge(phor, how='outer', on='date')

In [11]:
#Перевернуть таблицу
stat = stat.iloc[::-1].reset_index(drop=True)

In [12]:
#Удалил ненужную дату
stat = stat.drop(1, axis=0)

In [13]:
stat = stat.drop(0, axis=0)

In [14]:
stat

,date,pr_gema,pr_abrd,pr_alrs,pr_afks,pr_aflt,pr_bspb,pr_belu,pr_vtbr,pr_gazp,...,pr_nvtk,pr_pmsb,pr_pikk,pr_rosn,pr_mrkp,pr_rtkm,pr_rual,pr_sber,pr_sgzh,pr_phor
2,2021-08-29,902.5,195.5,145.83,30.97,69.40,74.80,3285.0,0.052400,317.94,...,1840.4,159.4,1388.5,555.40,0.2579,95.71,62.400,329.71,8.821,4724.0
3,2021-09-05,944.5,193.0,149.17,29.40,66.98,74.96,3176.0,0.051950,326.43,...,1913.0,156.4,1446.1,543.30,0.2735,93.20,72.130,326.25,8.681,4825.0
4,2021-09-12,924.5,193.0,143.80,29.08,66.80,77.26,3347.0,0.051400,334.50,...,1850.0,156.1,1484.8,567.10,0.2746,92.68,72.295,329.56,8.780,4937.0
5,2021-09-19,987.0,192.5,139.74,28.30,69.10,73.90,3422.0,0.050925,344.29,...,1884.6,157.0,1444.0,614.00,0.2612,92.38,73.195,325.44,8.683,5048.0
6,2021-09-26,NaN,193.0,138.01,27.19,70.00,76.51,3316.0,0.051485,363.25,...,1931.8,154.2,1278.0,618.45,0.2583,89.99,71.450,338.48,8.696,5115.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,2023-04-02,909.5,255.5,66.64,14.78,32.79,147.77,4430.0,0.018830,173.09,...,1228.2,157.7,659.1,391.70,0.2156,61.95,41.100,216.27,5.667,7213.0
82,2023-04-09,915.0,253.0,66.40,14.80,34.65,156.54,4489.0,0.018695,179.50,...,1296.0,166.3,654.6,392.40,0.2226,62.53,42.370,221.87,5.598,7185.0
83,2023-04-16,899.5,255.5,68.17,14.91,38.97,163.30,4598.0,0.020195,181.72,...,1321.4,165.1,659.3,398.75,0.2212,63.10,43.060,235.17,5.628,7330.0
84,2023-04-23,914.0,257.0,67.75,15.79,40.24,176.54,4172.0,0.022220,181.13,...,1340.8,172.6,688.9,393.80,0.2325,65.49,40.865,240.38,5.671,7276.0
85,2023-04-30,883.5,250.0,64.79,14.83,37.12,168.00,3983.0,0.021060,172.09,...,1222.0,169.1,645.4,378.65,0.2129,64.12,40.085,237.70,5.258,7061.0

In [17]:
stat.to_csv(r'data/stat_19.05.23.csv', index=False)